/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.UserInf.UserPanel;
import Interfaces.AdministratorInf.AdminPanel;
import Admin.Admin;
import Admin.AdminController;
import User.User;
import User.UserController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Namal Prdeep
 */


public class SystemLoginInf extends javax.swing.JFrame {

    /**
     * Creates new form SystemLoginInf
     */
    
    public SystemLoginInf() {
        initComponents();
        //setSize(900,650);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enteredId = new javax.swing.JTextField();
        enteredPassword = new javax.swing.JPasswordField();
        choosedAccountType = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 690, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Enter The Password:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Enter The ID:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Choose Account Type:");

        enteredId.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        enteredPassword.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enteredPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredPasswordActionPerformed(evt);
            }
        });

        choosedAccountType.setEditable(true);
        choosedAccountType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        choosedAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Account Type", "Admin Account", "User Account" }));
        choosedAccountType.setName("Admin\nUser"); // NOI18N
        choosedAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosedAccountTypeActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(51, 255, 0));
        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 0, 153));
        loginButton.setText("Login Now");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 153, 102));
        resetButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 0, 0));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        resetButton1.setBackground(new java.awt.Color(255, 0, 51));
        resetButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        resetButton1.setForeground(new java.awt.Color(255, 255, 255));
        resetButton1.setText("Exit");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredId, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choosedAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enteredId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enteredPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(choosedAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 530, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void choosedAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosedAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosedAccountTypeActionPerformed

    private void enteredPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteredPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteredPasswordActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        
        resetLoginFields();
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String enteredID,enteredPassword,accountType;
        
        enteredID=enteredId.getText();
        enteredPassword=this.enteredPassword.getText();
        accountType=choosedAccountType.getSelectedItem().toString();
        
        
        try{
            
            
            switch (accountType) {
                case "Select Your Account Type":
                    JOptionPane.showMessageDialog(null,"You Didn't Choose Account Type. Please Select One.");
                    resetLoginFields();
                    break;
                case "Admin Account":
                    //Admin panel Login Process
                    Admin admin1=new Admin();
                    admin1.setAdminID(enteredID);
                    admin1.setAdminPassword(enteredPassword);
                    boolean adminPass=AdminController.loginUser(admin1);
                    if(adminPass==false){
                        JOptionPane.showMessageDialog(null,"Please try Again! ID or Password Incorrect");
                        resetLoginFields();
                    }else{
                        //JOptionPane.showMessageDialog(null,"Yo got Admin panel");
                        AdminPanel adminPanel1=new AdminPanel();
                        adminPanel1.setVisible(true);
                        this.dispose();
                    }
                    break;
                case "User Account":
                    //User panel Login Process
                    User user1=new User();
                    user1.setUserID(enteredID);
                    user1.setUserPassword(enteredPassword);
                    boolean userPass=UserController.loginUser(user1);
                    if(userPass==false){
                        JOptionPane.showMessageDialog(null,"Please try Again! ID or Password Incorrect");
                        resetLoginFields();
                    }else{
                        //JOptionPane.showMessageDialog(null,"Yo got User panel");
                        UserPanel userpanel1=new UserPanel();
                        userpanel1.setVisible(true);
                        this.dispose();
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(null,"Please Select Account Type");
                    resetLoginFields();
                    break;
            }

        }catch(ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Driver is not Found!!!");
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"SQL Error!!!");
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_resetButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemLoginInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemLoginInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemLoginInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemLoginInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemLoginInf().setVisible(true);
            }
        });
    }
    
        void resetLoginFields(){
        enteredId.setText("");
        enteredPassword.setText("");
        choosedAccountType.setSelectedIndex(0);
        }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choosedAccountType;
    private javax.swing.JTextField enteredId;
    private javax.swing.JPasswordField enteredPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    // End of variables declaration//GEN-END:variables
}
