/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.UserInf;

import Interfaces.UserInf.UserPanel;
import Interfaces.AdministratorInf.ManageCustomerAdmins;
import Customer.Customer;
import Customer.CustomerController;
import DBConnection.DBConnector;
import Product.ProductController;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Namal Prdeep
 */
public class ManageCustomerUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageCustomers
     */
    public ManageCustomerUsers() throws ClassNotFoundException, SQLException {
        initComponents();
        setResizable(false);
        customerTableLoad();
    }

    
    //this method for load the customer table data inside gui table
    public void customerTableLoad() throws ClassNotFoundException,SQLException{
    
        ResultSet rs=CustomerController.getCustomers();
        manageCustomerTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
        //this method for set the table data to text boxes
    public void setCustomerTableData(){
    
        int r =manageCustomerTable.getSelectedRow();
        
        String cusID=manageCustomerTable.getValueAt(r,0).toString();
        String cusName=manageCustomerTable.getValueAt(r,1).toString();
        String eMail=manageCustomerTable.getValueAt(r,2).toString();
        String address=manageCustomerTable.getValueAt(r,3).toString();
        String telephone=manageCustomerTable.getValueAt(r,4).toString();
        String DOB=manageCustomerTable.getValueAt(r,5).toString();
        String gender=manageCustomerTable.getValueAt(r,6).toString();
        
        customerIDBox.setText(cusID);
        customerNameBox.setText(cusName);
        customerEmailBox.setText(eMail);
        customerAddressBox.setText(address);
        customerTelephoneBox.setText(telephone);
        customerDOBBox.setText(DOB);
        customerGenderBox.setText(gender);
        
    }
    
    //this for clear all texboxes
    public void clearFields(){
        
        customerIDBox.setText("");
        customerNameBox.setText("");
        customerEmailBox.setText("");
        customerAddressBox.setText("");
        customerTelephoneBox.setText("");
        customerDOBBox.setText("YYYY-MM-DD");
        customerGenderBox.setText("");
    }
    
    //this for search mechanism
    public void searchCustomer() throws ClassNotFoundException,SQLException{
    
        String srch=searchCustomerBox.getText();
        ResultSet rs=CustomerController.customerSearch(srch);
        manageCustomerTable.setModel(DbUtils.resultSetToTableModel(rs));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mangeCustomerBackButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchCustomerBox = new javax.swing.JTextField();
        customerAddressBox = new javax.swing.JTextField();
        customerNameBox = new javax.swing.JTextField();
        customerEmailBox = new javax.swing.JTextField();
        customerGenderBox = new javax.swing.JTextField();
        customerTelephoneBox = new javax.swing.JTextField();
        customerDOBBox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        updateCustomerButton = new javax.swing.JButton();
        addCustomerButton = new javax.swing.JButton();
        resetCustomerFieldsButton = new javax.swing.JButton();
        customerIDBox = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageCustomerTable = new javax.swing.JTable();
        customerBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mangeCustomerBackButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mangeCustomerBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mangeCustomerBackButton.setText("Manage Customers");
        jPanel1.add(mangeCustomerBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 780, 60));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Telephone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Date of Birth");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        searchCustomerBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchCustomerBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchCustomerBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerBox)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(searchCustomerBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerAddressBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        customerNameBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        customerEmailBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        customerGenderBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        customerTelephoneBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        customerDOBBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        customerDOBBox.setText("YYYY-MM-DD");

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        updateCustomerButton.setBackground(new java.awt.Color(204, 204, 255));
        updateCustomerButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateCustomerButton.setForeground(new java.awt.Color(51, 51, 51));
        updateCustomerButton.setText("Update");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerButton.setBackground(new java.awt.Color(51, 153, 0));
        addCustomerButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        resetCustomerFieldsButton.setBackground(new java.awt.Color(0, 102, 102));
        resetCustomerFieldsButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resetCustomerFieldsButton.setForeground(new java.awt.Color(255, 255, 255));
        resetCustomerFieldsButton.setText("Reset");
        resetCustomerFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCustomerFieldsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(updateCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(resetCustomerFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerButton)
                    .addComponent(updateCustomerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(resetCustomerFieldsButton)
                .addGap(23, 23, 23))
        );

        customerIDBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(customerAddressBox)
                            .addComponent(customerEmailBox)
                            .addComponent(customerTelephoneBox)
                            .addComponent(customerDOBBox)
                            .addComponent(customerGenderBox)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(customerIDBox, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerEmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(customerAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(customerTelephoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(customerDOBBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(customerGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 580));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCustomerTable.setBackground(new java.awt.Color(0, 255, 204));
        manageCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        manageCustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                manageCustomerTableMouseReleased(evt);
            }
        });
        manageCustomerTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                manageCustomerTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(manageCustomerTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 750, 580));

        customerBackButton.setBackground(new java.awt.Color(204, 204, 204));
        customerBackButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        customerBackButton.setForeground(new java.awt.Color(255, 0, 0));
        customerBackButton.setText("Back");
        customerBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(customerBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 650));

        setSize(new java.awt.Dimension(1186, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        
        try {
            Customer c1=new Customer();
            c1.setCustomerID(customerIDBox.getText());
            c1.setCustomerName(customerNameBox.getText());
            c1.setEmail(customerEmailBox.getText());
            c1.setAddress(customerAddressBox.getText());
            c1.setContactNumber(Integer.parseInt(customerTelephoneBox.getText()));
            c1.setDateOfBirth(customerDOBBox.getText());
            c1.setGender(customerGenderBox.getText());
            
            int i=CustomerController.addCustomer(c1);
            if(i!=0){
                JOptionPane.showMessageDialog(null,"Customer Added");
                customerTableLoad();
                clearFields();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomerAdmins.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomerAdmins.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void customerBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBackButtonActionPerformed
        
        UserPanel userpanel2=new UserPanel();
        userpanel2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_customerBackButtonActionPerformed

    private void resetCustomerFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCustomerFieldsButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_resetCustomerFieldsButtonActionPerformed

    private void manageCustomerTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageCustomerTableKeyReleased
        
        setCustomerTableData();
        
    }//GEN-LAST:event_manageCustomerTableKeyReleased

    private void manageCustomerTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerTableMouseReleased
        
        setCustomerTableData();
        
    }//GEN-LAST:event_manageCustomerTableMouseReleased

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        
        try {
            Customer c2=new Customer();
            c2.setCustomerID(customerIDBox.getText());
            c2.setCustomerName(customerNameBox.getText());
            c2.setEmail(customerEmailBox.getText());
            c2.setAddress(customerAddressBox.getText());
            c2.setContactNumber(Integer.parseInt(customerTelephoneBox.getText()));
            c2.setDateOfBirth(customerDOBBox.getText());
            c2.setGender(customerGenderBox.getText());
            
            
            int i=CustomerController.updateCustomer(c2);
            if(i!=0){
                JOptionPane.showMessageDialog(null,"Customer Updated");
                customerTableLoad();
                clearFields();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomerAdmins.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomerAdmins.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void searchCustomerBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerBoxKeyReleased
        
        try {
            searchCustomer();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomerUsers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomerUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchCustomerBoxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageCustomerUsers().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageCustomerUsers.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageCustomerUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField customerAddressBox;
    private javax.swing.JButton customerBackButton;
    private javax.swing.JTextField customerDOBBox;
    private javax.swing.JTextField customerEmailBox;
    private javax.swing.JTextField customerGenderBox;
    private javax.swing.JTextField customerIDBox;
    private javax.swing.JTextField customerNameBox;
    private javax.swing.JTextField customerTelephoneBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageCustomerTable;
    private javax.swing.JLabel mangeCustomerBackButton;
    private javax.swing.JButton resetCustomerFieldsButton;
    private javax.swing.JTextField searchCustomerBox;
    private javax.swing.JButton updateCustomerButton;
    // End of variables declaration//GEN-END:variables
}
