/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.AdministratorInf;

import Interfaces.SystemLoginInf;
import TaskTrack.TaskTrack;
import TaskTrack.TaskTrackController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Namal Prdeep
 */
public class AdminPanel extends javax.swing.JFrame {

 
    public AdminPanel() {
        initComponents();
        //setSize(900,650);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        AdminManageCutomerButton = new javax.swing.JButton();
        adminManageCustomerButton = new javax.swing.JButton();
        adminTaskTrackButton = new javax.swing.JButton();
        adminInvoiceGenerateButton = new javax.swing.JButton();
        adminSystemUserManageButton = new javax.swing.JButton();
        adminPanelexitButton = new javax.swing.JButton();
        adminTaskTrackButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 799, 55));

        logOutButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        logOutButton.setText("LogOut");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 220, 39));

        AdminManageCutomerButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        AdminManageCutomerButton.setText("Manage Customers");
        AdminManageCutomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminManageCutomerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AdminManageCutomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 356, 39));

        adminManageCustomerButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminManageCustomerButton.setText("Manage Products");
        adminManageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminManageCustomerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminManageCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 356, 39));

        adminTaskTrackButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminTaskTrackButton.setText("Show All Generated Invoices");
        adminTaskTrackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTaskTrackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminTaskTrackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 356, 39));

        adminInvoiceGenerateButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminInvoiceGenerateButton.setText("Invoice Generation");
        adminInvoiceGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInvoiceGenerateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminInvoiceGenerateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 356, 39));

        adminSystemUserManageButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminSystemUserManageButton.setText("Manage System Users");
        adminSystemUserManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSystemUserManageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminSystemUserManageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 356, 39));

        adminPanelexitButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminPanelexitButton.setText("Exit");
        adminPanelexitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPanelexitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminPanelexitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 220, 39));

        adminTaskTrackButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminTaskTrackButton1.setText("Task Tracks");
        adminTaskTrackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTaskTrackButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(adminTaskTrackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 356, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(916, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelexitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPanelexitButtonActionPerformed
        
        try {
            TaskTrack t1=new TaskTrack();
            t1.setTaskInformation("Admin Logged out from the System");
            TaskTrackController.addTask(t1);
            System.exit(0);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminPanelexitButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        
        try {
            SystemLoginInf sys1=new SystemLoginInf();
            
            TaskTrack t1=new TaskTrack();
            t1.setTaskInformation("Admin Logged out from the System");
            TaskTrackController.addTask(t1);
            
            sys1.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void AdminManageCutomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminManageCutomerButtonActionPerformed
        try {
            ManageCustomerAdmins manageCustomer1=new ManageCustomerAdmins();
            manageCustomer1.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AdminManageCutomerButtonActionPerformed

    private void adminManageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminManageCustomerButtonActionPerformed
        
        try {
            ManageProductAdmins manageProduct1=new ManageProductAdmins();
            manageProduct1.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_adminManageCustomerButtonActionPerformed

    private void adminInvoiceGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInvoiceGenerateButtonActionPerformed

        try {
            InvoiceGenerateStep01Admin st1=new InvoiceGenerateStep01Admin();
            st1.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_adminInvoiceGenerateButtonActionPerformed

    private void adminTaskTrackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTaskTrackButtonActionPerformed
        
        try {
            ShowGeneratedInvoicesAdmin showInvoices1=new ShowGeneratedInvoicesAdmin();
            showInvoices1.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_adminTaskTrackButtonActionPerformed

    private void adminTaskTrackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTaskTrackButton1ActionPerformed
        
        try {
            TasksTracksAdmin track1=new TasksTracksAdmin();
            track1.setVisible(true);
            this.dispose();
                    
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_adminTaskTrackButton1ActionPerformed

    private void adminSystemUserManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSystemUserManageButtonActionPerformed
        
        ManageSystemUser sysUser1=new ManageSystemUser();
        sysUser1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adminSystemUserManageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminManageCutomerButton;
    private javax.swing.JButton adminInvoiceGenerateButton;
    private javax.swing.JButton adminManageCustomerButton;
    private javax.swing.JButton adminPanelexitButton;
    private javax.swing.JButton adminSystemUserManageButton;
    private javax.swing.JButton adminTaskTrackButton;
    private javax.swing.JButton adminTaskTrackButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutButton;
    // End of variables declaration//GEN-END:variables
}
