/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.AdministratorInf;

import Admin.Admin;
import Interfaces.*;
import Admin.AdminController;
import DBConnection.DBConnector;
import User.User;
import User.UserController;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Namal Prdeep
 */
public class ManageSystemUser extends javax.swing.JFrame {

    /**
     * Creates new form ManageCustomers
     */
    public ManageSystemUser() {
        initComponents();
        setResizable(false);
        adminTableLoad();
        userTableLoad();
    }

    
    //admin table loading function
    public void adminTableLoad(){
    
        try {
            ResultSet rs=AdminController.getAdminAccounts();
            adminAccTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //user table loading function
    public void userTableLoad(){
    
        try {
            Connection con=DBConnector.getConnection();
            Statement stmt=con.createStatement();
            String sql="SELECT * FROM user";
            ResultSet rs=stmt.executeQuery(sql);
            userAccTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //clear fields in account controller
    public void clearAdminFields(){
    
        adminIDBox.setText("");
        adminNameBox.setText("");
        adminPasswordBox.setText("");
    }
    
     //clear fields in account controller
    public void clearUserFields(){
    
        userIDBox.setText("");
        userNameBox.setText("");
        userPasswordBox.setText("");
    }
    //set admin table data to its text fields
    public void setAdminTableData(){
    
        int r=adminAccTable.getSelectedRow();
        
        String adminID=adminAccTable.getValueAt(r,0).toString();
        String adminName=adminAccTable.getValueAt(r,1).toString();
        String adminPassword=adminAccTable.getValueAt(r,2).toString();
        
        adminIDBox.setText(adminID);
        adminNameBox.setText(adminName);
        adminPasswordBox.setText(adminPassword);
    }
    
    //set user table data to its text fields
    public void setUserTableData(){
    
        int r=userAccTable.getSelectedRow();
        
        String userID=userAccTable.getValueAt(r,0).toString();
        String userName=userAccTable.getValueAt(r,1).toString();
        String userPassword=userAccTable.getValueAt(r,2).toString();
        
        userIDBox.setText(userID);
        userNameBox.setText(userName);
        userPasswordBox.setText(userPassword);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminPasswordBox = new javax.swing.JTextField();
        adminIDBox = new javax.swing.JTextField();
        adminNameBox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        adminUpdateButton = new javax.swing.JButton();
        addAdminButton = new javax.swing.JButton();
        adminDeleteButton = new javax.swing.JButton();
        adminFieldsResetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminAccTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userPasswordBox = new javax.swing.JTextField();
        userIDBox = new javax.swing.JTextField();
        userNameBox = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        userUpdateButton = new javax.swing.JButton();
        userAddButton = new javax.swing.JButton();
        userDeleteButton = new javax.swing.JButton();
        userFieldResetButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userAccTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage System Users");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 780, 60));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Admin ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Admin Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Admin Password:");

        adminPasswordBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        adminPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordBoxActionPerformed(evt);
            }
        });

        adminIDBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        adminNameBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        adminUpdateButton.setBackground(new java.awt.Color(204, 204, 255));
        adminUpdateButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        adminUpdateButton.setForeground(new java.awt.Color(51, 51, 51));
        adminUpdateButton.setText("Update");
        adminUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUpdateButtonActionPerformed(evt);
            }
        });

        addAdminButton.setBackground(new java.awt.Color(51, 153, 0));
        addAdminButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        addAdminButton.setText("Add");
        addAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminButtonActionPerformed(evt);
            }
        });

        adminDeleteButton.setBackground(new java.awt.Color(51, 0, 51));
        adminDeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        adminDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        adminDeleteButton.setText("Delete");
        adminDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDeleteButtonActionPerformed(evt);
            }
        });

        adminFieldsResetButton.setBackground(new java.awt.Color(0, 102, 102));
        adminFieldsResetButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        adminFieldsResetButton.setForeground(new java.awt.Color(255, 255, 255));
        adminFieldsResetButton.setText("Reset");
        adminFieldsResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminFieldsResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminFieldsResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(addAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(adminDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAdminButton)
                    .addComponent(adminUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminFieldsResetButton)
                    .addComponent(adminDeleteButton))
                .addGap(22, 22, 22))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Admin Account Control");

        adminAccTable.setBackground(new java.awt.Color(255, 255, 0));
        adminAccTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        adminAccTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminAccTableMouseReleased(evt);
            }
        });
        adminAccTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminAccTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(adminAccTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adminIDBox)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adminNameBox)
                                                .addGap(7, 7, 7))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adminPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 3, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adminIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adminNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adminPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 420, 580));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 10, 90, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage System Users");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 780, 60));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("User ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("User Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("User Password:");

        userPasswordBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordBoxActionPerformed(evt);
            }
        });

        userIDBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        userNameBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        userUpdateButton.setBackground(new java.awt.Color(204, 204, 255));
        userUpdateButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userUpdateButton.setForeground(new java.awt.Color(51, 51, 51));
        userUpdateButton.setText("Update");
        userUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userUpdateButtonActionPerformed(evt);
            }
        });

        userAddButton.setBackground(new java.awt.Color(51, 153, 0));
        userAddButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userAddButton.setForeground(new java.awt.Color(255, 255, 255));
        userAddButton.setText("Add");
        userAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddButtonActionPerformed(evt);
            }
        });

        userDeleteButton.setBackground(new java.awt.Color(51, 0, 51));
        userDeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        userDeleteButton.setText("Delete");
        userDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteButtonActionPerformed(evt);
            }
        });

        userFieldResetButton.setBackground(new java.awt.Color(0, 102, 102));
        userFieldResetButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userFieldResetButton.setForeground(new java.awt.Color(255, 255, 255));
        userFieldResetButton.setText("Reset");
        userFieldResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userFieldResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(userAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(userDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAddButton)
                    .addComponent(userUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFieldResetButton)
                    .addComponent(userDeleteButton))
                .addGap(22, 22, 22))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("User Account Control");

        userAccTable.setBackground(new java.awt.Color(204, 255, 0));
        userAccTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userAccTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userAccTableMouseReleased(evt);
            }
        });
        userAccTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userAccTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(userAccTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userNameBox))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userPasswordBox))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userIDBox)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(userNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(userPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 420, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        setSize(new java.awt.Dimension(916, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        AdminPanel admin1=new AdminPanel();
        admin1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void adminFieldsResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFieldsResetButtonActionPerformed
        clearAdminFields();
    }//GEN-LAST:event_adminFieldsResetButtonActionPerformed

    private void addAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminButtonActionPerformed
        
        try {
            Admin admin=new Admin();
            admin.setAdminID(adminIDBox.getText());
            admin.setAdminName(adminNameBox.getText());
            admin.setAdminPassword(adminPasswordBox.getText());
            
            int i=AdminController.addNewAdmin(admin);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"A New Admin Account Created");
                clearAdminFields();
                adminTableLoad();
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addAdminButtonActionPerformed

    private void adminPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordBoxActionPerformed

    private void userPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordBoxActionPerformed

    private void userAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddButtonActionPerformed
        
        try {
            User user1=new User();
            user1.setUserID(userIDBox.getText());
            user1.setUserName(userNameBox.getText());
            user1.setUserPassword(userPasswordBox.getText());
            
            int i=UserController.addNewUser(user1);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"A New User Account Created");
                clearUserFields();
                userTableLoad();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_userAddButtonActionPerformed

    private void userFieldResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldResetButtonActionPerformed
        clearUserFields();
    }//GEN-LAST:event_userFieldResetButtonActionPerformed

    private void adminAccTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminAccTableKeyReleased
        setAdminTableData();
    }//GEN-LAST:event_adminAccTableKeyReleased

    private void adminAccTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminAccTableMouseReleased
        setAdminTableData();
    }//GEN-LAST:event_adminAccTableMouseReleased

    private void userAccTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userAccTableKeyReleased
        setUserTableData();
    }//GEN-LAST:event_userAccTableKeyReleased

    private void userAccTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccTableMouseReleased
        setUserTableData();
    }//GEN-LAST:event_userAccTableMouseReleased

    private void adminUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUpdateButtonActionPerformed
        
        try {
            Admin admin=new Admin();
            admin.setAdminID(adminIDBox.getText());
            admin.setAdminName(adminNameBox.getText());
            admin.setAdminPassword(adminPasswordBox.getText());
            
            int i=AdminController.updateAdmin(admin);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"An Admin Account Updated");
                clearAdminFields();
                adminTableLoad();
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_adminUpdateButtonActionPerformed

    private void adminDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDeleteButtonActionPerformed
        
        try {
            Admin admin=new Admin();
            admin.setAdminID(adminIDBox.getText());

            int i=AdminController.deleteAdmin(admin);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"An Admin Account Deleted");
                clearAdminFields();
                adminTableLoad();
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_adminDeleteButtonActionPerformed

    private void userUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userUpdateButtonActionPerformed
        
        try {
            User user1=new User();
            user1.setUserID(userIDBox.getText());
            user1.setUserName(userNameBox.getText());
            user1.setUserPassword(userPasswordBox.getText());
            
            int i=UserController.updateUser(user1);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"An User Account Updated");
                clearUserFields();
                userTableLoad();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_userUpdateButtonActionPerformed

    private void userDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteButtonActionPerformed
        
        try {
            User user1=new User();
            user1.setUserID(userIDBox.getText());
            user1.setUserName(userNameBox.getText());
            user1.setUserPassword(userPasswordBox.getText());
            
            int i=UserController.deleteUser(user1);
            
            if(i!=0){
                JOptionPane.showMessageDialog(null,"An User Account Deleted");
                clearUserFields();
                userTableLoad();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSystemUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_userDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSystemUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdminButton;
    private javax.swing.JTable adminAccTable;
    private javax.swing.JButton adminDeleteButton;
    private javax.swing.JButton adminFieldsResetButton;
    private javax.swing.JTextField adminIDBox;
    private javax.swing.JTextField adminNameBox;
    private javax.swing.JTextField adminPasswordBox;
    private javax.swing.JButton adminUpdateButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable userAccTable;
    private javax.swing.JButton userAddButton;
    private javax.swing.JButton userDeleteButton;
    private javax.swing.JButton userFieldResetButton;
    private javax.swing.JTextField userIDBox;
    private javax.swing.JTextField userNameBox;
    private javax.swing.JTextField userPasswordBox;
    private javax.swing.JButton userUpdateButton;
    // End of variables declaration//GEN-END:variables
}
